ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
IMAGE_NAME = "bento/centos-7"

Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 500
  config.vm.box = IMAGE_NAME

  # Virtualbox configuration
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.gui = false
    vb.linked_clone = true
    vb.memory = 2048
  end

  # config.vm.provision "shell", path: "install-kubeadm.sh"

  # K8s master configuration
  master_name = "k8s-master"
  config.vm.define master_name do |master|
    master.vm.network "private_network", ip: "192.168.50.2"
    master.vm.hostname = master_name
  end

  # K8s worker configuration
  2.times do |n|
    worker_name = "k8s-worker-#{n}"
    config.vm.define worker_name do |worker|
      worker.vm.network "private_network", ip: "192.168.50.#{n + 3}"
      worker.vm.hostname = worker_name
    end
  end

  # Ansible configuration
  config.vm.provision "ansible_local" do |ansible|
    ansible.config_file = "ansible.cfg"
    ansible.playbook = "playbook.yml"
    ansible.groups = {
        masters: ["k8s-master"],
        nodes: ["k8s-node-1","k8s-node-2"]
    }
  end
end
