ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
IMAGE_NAME = "bento/ubuntu-16.04"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.boot_timeout = 500
  config.vm.box = IMAGE_NAME

  # Virtualbox configuration
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.gui = false
    vb.linked_clone = true
    vb.memory = 2048
  end

  # K8s master configuration
  config.vm.define "k8s-master" do |master|
    master.vm.network "private_network", ip: "192.168.50.10"
    master.vm.hostname = "k8s-master"
  end

  # K8s worker configuration
  2.times do |n|
    config.vm.define "k8s-node-#{n}" do |node|
      node.vm.network "private_network", ip: "192.168.50.#{n + 11}"
      node.vm.hostname = "k8s-node-#{n}"
    end
  end

  # Ansible configuration
  config.vm.provision "ansible_local" do |ansible|
    ansible.config_file = "ansible.cfg"
    ansible.playbook = "playbook.yml"
    ansible.groups = {
        masters: ["k8s-master"],
        nodes: ["k8s-node-0","k8s-node-1"]
    }
  end
end
